name: {{cookiecutter.name}}
channels:
  - defaults
  - conda-forge
  - DistrictDataLabs
dependencies:
  # conf
  - toml
  # flow
  - mlflow
  - papermill
  # edit
  - ipython
  - jupytext
  - jupyterlab
  - ipywidgets
  # learn
  # - tpot
  # - hdbscan
  # - xgboost
  # - tensorflow
  - scikit-learn
  # create
  # - patsy
  # - sympy
  # - boruta_py
  # - statsmodels
  # - featuretools
  # explain
  # - shap
  # analyze
  # - dask
  - numpy
  - pandas
  - pandas-profiling
  # visualize
  - seaborn
  - matplotlib
  - yellowbrick
  - pip:
    - "--editable ."
